#!/bin/bash

# Exit build script on first failure
set -e

# Echo commands to stdout.
set -x

# Location of app source files.
SOURCE_DIR=line_length_linter

# Delete pyc files from previous builds.
find . -name "*.pyc" -delete

# Check that source has correct formatting.
yapf --diff --recursive --style google ./ --exclude=./third_party/*

# Run static analysis for Python bugs/cruft.
pyflakes "${SOURCE_DIR}/"

# Check docstrings for style consistency.
PYTHONPATH=$PYTHONPATH:$(pwd)/third_party/docstringchecker:$(pwd)/line_length_linter \
  pylint --reports=n --rcfile=.pylintrc "$SOURCE_DIR" "$TEST_DIR"

